import Head from "next/head";
import ChakraUiProvider from "./chakra-ui-provider";
import "./globals.css";
import SidebarWithHeader from "./components/sidebar";

export const metadata = {
  title: "Mitec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body>
        <ChakraUiProvider>
          <SidebarWithHeader>{children}</SidebarWithHeader>
        </ChakraUiProvider>
      </body>
    </html>
  );
}
