import ChakraUiProvider from "./chakra-ui-provider";

export const metadata = {
  title: "Mitec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraUiProvider>{children}</ChakraUiProvider>
      </body>
    </html>
  );
}
