//https://mitec.itesm.mx/_vti_bin/orion.svc/MisServicios

interface ServiceInterface {
  Acceso: string;
  Agrupacion: string;
  Categoria: string;
  Clave: string;
  Descripcion: string;
  Favorito: boolean;
  FechaCreacion: string;
  FechaExpiracion: {
    FormatoISO: string | null;
    Milisegundos: string;
  };
  FechaPublicacion: {
    FormatoISO: string;
    Milisegundos: string;
  };
  Icono: string;
  Id: number;
  ImagenFondo: string;
  Nombre: string;
  OrdenRecomendado: number;
  PaginaIntermedia: string;
  PalabrasClave: string;
  Popularidad: number;
  Subcategoria: string;
  TipoIntegracion: string;
  URL: string;
}

const SERVICES: ServiceInterface[] = [
  {
    Acceso: "",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_DDSA_010",
    Descripcion:
      "Datos que implican toda aquella información inherente a una persona y que permiten identificarla",
    Favorito: false,
    FechaCreacion: "/Date(1606945993000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 17:00:00 -06:00",
      Milisegundos: "/Date(1554764400000-0600)/",
    },
    Icono: "https://i.imgur.com/nVlofu6.png",
    Id: 8,
    ImagenFondo: "",
    Nombre: "Consulta de datos generales",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Actualización | datos | contacto |actualizacion \t | Update | data | Contact",
    Popularidad: 0,
    Subcategoria: "Mi perfil",
    TipoIntegracion: "En sitio",
    URL: "https://alsvdbw01.itesm.mx/servesc/plsql/swgdatospers_itesm.inicio",
  },
  {
    Acceso: "",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_DDSA_007",
    Descripcion: "Consulta de horario del alumno",
    Favorito: false,
    FechaCreacion: "/Date(1606945998000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 17:00:00 -06:00",
      Milisegundos: "/Date(1554764400000-0600)/",
    },
    Icono: "https://i.imgur.com/8Vw0LUE.png",
    Id: 9,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/horario.png",
    Nombre: "Consulta de horario",
    OrdenRecomendado: 1,
    PaginaIntermedia: "",
    PalabrasClave: "consulta | consultas | horario | materias | clases",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://alsvdbw01.itesm.mx/servesc/plsql/swghorario_itesm.inicio",
  },
  {
    Acceso: "",
    Agrupacion: "#Mi Información#Escolar",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_DDSA_018_t21",
    Descripcion:
      "Consulta de las unidades de formación que el alumno cursó, las actividades formativas y las unidades de formación que solicitó revalidación ante la SEP.",
    Favorito: false,
    FechaCreacion: "/Date(1606945913000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-11-01 00:00:00 -06:00",
      Milisegundos: "/Date(1572588000000-0600)/",
    },
    Icono: "https://i.imgur.com/4ZOWTRn.png",
    Id: 10,
    ImagenFondo: "",
    Nombre: "Unidades de Formación cursadas",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "calificaciones | notas | boleta | calificación de materias | materias | evaluación | calificación | unidades | formación",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/Paginas/servicios/materias-acreditadas/index.aspx",
  },
  {
    Acceso: "",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_DDSA_009",
    Descripcion: "",
    Favorito: false,
    FechaCreacion: "/Date(1606945919000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 17:00:00 -06:00",
      Milisegundos: "/Date(1554764400000-0600)/",
    },
    Icono: "https://i.imgur.com/76TTaRe.png",
    Id: 11,
    ImagenFondo: "",
    Nombre: "Exámenes y certificados",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Examen | exámenes | evaluación | evaluaciones | certificado | certificados",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://alsvdbw01.itesm.mx/servesc/plsql/swgexamenes_itesm.inicio",
  },
  {
    Acceso: "",
    Agrupacion: "#Escolar",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_CALENDARIO",
    Descripcion:
      "Consulta de calendarios académicos de programas semestrales, tetramestrales y trimestrales, de todos los niveles académicos (Preparatoria, Licenciatura, Maestría y Doctorado)",
    Favorito: false,
    FechaCreacion: "/Date(1606945925000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 17:00:00 -06:00",
      Milisegundos: "/Date(1554764400000-0600)/",
    },
    Icono: "https://i.imgur.com/B6ylREW.png",
    Id: 12,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Mas_visitados/calendario.png",
    Nombre: "Consulta del calendario escolar",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "calendarios | fechas | calendario\t | calendars | dates | calendar | schedule",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://portalrep.itesm.mx/alumnos/calendarios/1.htm",
  },
  {
    Acceso: "",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_DDSA_049",
    Descripcion: "Consulta los apoyos financieros que se te han otorgado",
    Favorito: false,
    FechaCreacion: "/Date(1606945939000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/jpPSgNj.png",
    Id: 17,
    ImagenFondo:
      "https://mitec.itesm.mx/AlumnosTEC20/PublishingImages/Recomendados/apoyo%20educativo.png",
    Nombre: "Mis apoyos educativos",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Becas | crédito educativo | apoyo educativo | beca | crédito | educativo",
    Popularidad: 0,
    Subcategoria: "Becas y Créditos",
    TipoIntegracion: "Nueva ventana",
    URL: "https://alsvdbw01.itesm.mx/servesc/plsql/bwghistoriabecario_itesm.inicio",
  },
  {
    Acceso: "",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_EdoCta",
    Descripcion:
      "Consulta del estado de cuenta, pagos realizados y pagos pendientes, así como información para facturación.",
    Favorito: false,
    FechaCreacion: "/Date(1606945951000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/4fHWRWO.png",
    Id: 19,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/Edo.%20cuenta.png",
    Nombre: "Estado de cuenta y pago de colegiaturas",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "cuenta | pagos | colegiatura | pago | estado\t | account | payments | tuition | payment | condition",
    Popularidad: 0,
    Subcategoria: "Servicios de Tesoreria",
    TipoIntegracion: "Nueva ventana",
    URL: "https://estadodecuenta.tec.mx/auth/login?returnUrl=perfil",
  },
  {
    Acceso: "",
    Agrupacion: "#TesorerÍa",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_TIENDAV_V_2018",
    Descripcion:
      "Utiliza este servicio para realizar el pago en linea de servicios diferentes a la colegiatura",
    Favorito: false,
    FechaCreacion: "/Date(1606945966000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/j1m3GuL.png",
    Id: 22,
    ImagenFondo: "",
    Nombre: "Tienda Virtual",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Tienda en línea | Tec Store | compras\r\n",
    Popularidad: 0,
    Subcategoria: "Tec Store",
    TipoIntegracion: "Nueva ventana",
    URL: "https://catalogodeservicios.itesm.mx/InicioMiTecAlumnos.aspx",
  },
  {
    Acceso: "",
    Agrupacion: "#TesorerÍa",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_CFDDATOSFACTURA",
    Descripcion: "",
    Favorito: false,
    FechaCreacion: "/Date(1606945966000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/9NZlSbd.png",
    Id: 24,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/facturacion%20electronica.png",
    Nombre: "Facturación electronica",
    OrdenRecomendado: 1,
    PaginaIntermedia: "",
    PalabrasClave: "Factura | facturación | electrónica",
    Popularidad: 0,
    Subcategoria: "Servicios de Tesoreria",
    TipoIntegracion: "Nueva ventana",
    URL: "https://tec.cdc.origon.cloud/",
  },
  {
    Acceso: "",
    Agrupacion: "#TesorerÍa#Seguros y Bienestar",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS001",
    Descripcion:
      "En este servicio podrás encontrar las pólizas y solicitar las  facturas de seguros contratados",
    Favorito: false,
    FechaCreacion: "/Date(1606945967000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/2QdEYGo.png",
    Id: 26,
    ImagenFondo: "",
    Nombre: "Información y facturas de seguros",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Factura | facturas | seguro | seguros | facturación",
    Popularidad: 0,
    Subcategoria: "Seguros y Bienestar",
    TipoIntegracion: "Nueva ventana",
    URL: "https://fs.itesm.mx/adfs/ls/idpinitiatedsignon.aspx?loginToRp=https://www.segurosmnyl.com.mx/itesm/AccesoAlumnos.aspx",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS_OnJobs",
    Descripcion:
      "On Campus Interns tiene como propósito atraer a los mejores estudiantes para que trabajen en desafíos de alto impacto en el campus",
    Favorito: false,
    FechaCreacion: "/Date(1606945968000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/Nn3I1lz.jpg",
    Id: 27,
    ImagenFondo: "",
    Nombre: "On Campus Interns ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "campus | interns | job | practicantes",
    Popularidad: 0,
    Subcategoria: "Centro de Vinculación y Desarrollo Profesional",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_VESTUDIANTIL/Centro%20de%20Vinculacion%20y%20Desarrollo%20Profesional/OncampusJobs/index.html",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_FIRM_CODETIC",
    Descripcion:
      "En este espacio podrás consultar y reafirmar tu compromiso con la Integridad Académica.",
    Favorito: false,
    FechaCreacion: "/Date(1606945972000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-06-06 10:00:00 -06:00",
      Milisegundos: "/Date(1559836800000-0600)/",
    },
    Icono: "https://i.imgur.com/BuWX8Td.png",
    Id: 38,
    ImagenFondo: "",
    Nombre: "Firma de Código de Integridad Académica",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Firma | código | códigos | integridad | académica",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://sitiosmiespacio.itesm.mx/publicos/evaluacionescsc/Paginas/Codigo%20Integridad%20%20Acad%C3%A9mica/CodAcad1.html ",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_PROTOCOLO_VIOLENCIA",
    Descripcion: "Reglamentos",
    Favorito: false,
    FechaCreacion: "/Date(1606945973000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-06-06 10:00:00 -06:00",
      Milisegundos: "/Date(1559836800000-0600)/",
    },
    Icono: "https://i.imgur.com/BuWX8Td.png",
    Id: 41,
    ImagenFondo: "",
    Nombre: "Protocolo de Violencia de Género",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "protocolo | violencia | genero | integridad | protocolos",
    Popularidad: 0,
    Subcategoria: "Seguros y Bienestar",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitec.itesm.mx/sites/talentoycultura/protocolo/protocolo.html",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_CÓDIGO DE ÉTICA",
    Descripcion: "Reglamentos",
    Favorito: false,
    FechaCreacion: "/Date(1606945973000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-06-06 10:00:00 -06:00",
      Milisegundos: "/Date(1559836800000-0600)/",
    },
    Icono: "https://i.imgur.com/BuWX8Td.png",
    Id: 42,
    ImagenFondo: "",
    Nombre: "Código de integridad académica",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "código | codigo | integridad | académica | academica",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://portalrep.itesm.mx/alumnos/reglamentos/c_etica.pdf",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_CÓDIGO DE ÉTICA_ing",
    Descripcion: "Reglamentos",
    Favorito: false,
    FechaCreacion: "/Date(1606945974000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-06-06 10:00:00 -06:00",
      Milisegundos: "/Date(1559836800000-0600)/",
    },
    Icono: "https://i.imgur.com/BuWX8Td.png",
    Id: 43,
    ImagenFondo: "",
    Nombre: "Student Code of Honor",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "student | students | code | honor | código",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://portalrep.itesm.mx/alumnos/reglamentos/c_honor.pdf",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_REG_ACAD_PROF_ING",
    Descripcion: "Reglamentos",
    Favorito: false,
    FechaCreacion: "/Date(1606945979000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-06-06 10:00:00 -06:00",
      Milisegundos: "/Date(1559836800000-0600)/",
    },
    Icono: "https://i.imgur.com/BuWX8Td.png",
    Id: 53,
    ImagenFondo: "",
    Nombre: "Academic regulations for undergraduate students",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "ungraduate | regulations | regulation | student | graduate",
    Popularidad: 0,
    Subcategoria: "Reglamentos",
    TipoIntegracion: "En sitio",
    URL: "https://portalrep.itesm.mx/na/normatividad_academica/documentos/reglamento/academico/reglamento_academico_profesional_eng.pdf",
  },
  {
    Acceso: "3: JWT",
    Agrupacion: "#LIFE",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS_CITAS",
    Descripcion: "Solicitud de citas ",
    Favorito: false,
    FechaCreacion: "/Date(1606945983000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-08-27 00:00:00 -06:00",
      Milisegundos: "/Date(1566885600000-0600)/",
    },
    Icono: "https://i.imgur.com/qEsltWD.png",
    Id: 62,
    ImagenFondo: "",
    Nombre: "Solicitud de citas",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Solicitud | cita | citas | reunión",
    Popularidad: 0,
    Subcategoria: "LiFE - Liderazgo y Formacion Estudiantil",
    TipoIntegracion: "Nueva ventana",
    URL: "https://micrmteccommunity.force.com/solicitudcitas/apex/appointment",
  },
  {
    Acceso: "",
    Agrupacion: "#Acreditaciones#Escolar",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_MATEREMEDIAL_T21",
    Descripcion:
      "Si tomaste uno o varios módulos de Matemáticas MOOC El Cálculo, ofrecidos en la plataforma COURSERA (Modelo lineal, Modelo cuadrático, Modelo cúbico y otros Modelos) ",
    Favorito: false,
    FechaCreacion: "/Date(1606945984000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-07-04 12:00:00 -06:00",
      Milisegundos: "/Date(1562263200000-0600)/",
    },
    Icono: "https://i.imgur.com/j2wCyRh.png",
    Id: 63,
    ImagenFondo: "",
    Nombre: "Acreditación por certificado COURSERA Matemáticas ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Acreditación | certificado | coursera | matemáticas",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Admitidos/01_T21.html",
  },
  {
    Acceso: "",
    Agrupacion: "#Acreditaciones#Escolar",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_FISICREMEDIAL_T21",
    Descripcion:
      "Si tomaste uno o los dos módulos de Física MOOC ofrecidos en la plataforma COURSERA (Dimensión y movimiento y Vectores, trabajo y energía) ",
    Favorito: false,
    FechaCreacion: "/Date(1606945984000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-07-04 12:00:00 -06:00",
      Milisegundos: "/Date(1562263200000-0600)/",
    },
    Icono: "https://i.imgur.com/j2wCyRh.png",
    Id: 64,
    ImagenFondo: "",
    Nombre: "Acreditación por certificado COURSERA Física ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Acreditación | certificado | coursera | física",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Admitidos/047_T21.html",
  },
  {
    Acceso: "",
    Agrupacion: "#Acreditaciones#Escolar",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_Funespanol_T21",
    Descripcion:
      "Si tomaste uno o varios módulos de Fundamentos de Escritura MOOC ofrecidos en la plataforma COURSERA (Fundamentos de la escritura y Fundamentos de la escritura académica)",
    Favorito: false,
    FechaCreacion: "/Date(1606945985000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-07-04 12:00:00 -06:00",
      Milisegundos: "/Date(1562263200000-0600)/",
    },
    Icono: "https://i.imgur.com/j2wCyRh.png",
    Id: 65,
    ImagenFondo: "",
    Nombre: "Acreditación por certificado COURSERA Fundamentos de Escritura ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Acreditación | certificado | coursera | fundamentos | escritura",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Admitidos/02_T21.html",
  },
  {
    Acceso: "",
    Agrupacion: "#TesorerÍa",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_REMBOLSO_2015 ",
    Descripcion:
      "A través de este servicio podrás solicitar el reembolso de un pago.",
    Favorito: false,
    FechaCreacion: "/Date(1606945985000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-07-01 15:00:00 -06:00",
      Milisegundos: "/Date(1562014800000-0600)/",
    },
    Icono: "https://i.imgur.com/V4IhSMS.png",
    Id: 67,
    ImagenFondo: "",
    Nombre: "Solicitud de reembolso ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Solicitud | reembolso | reembolsos | devolución",
    Popularidad: 0,
    Subcategoria: "Servicios de Tesoreria",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/GDC/Reembolsos",
  },
  {
    Acceso: "",
    Agrupacion: "#Acreditaciones#Escolar",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_Introcomputo_T21",
    Descripcion:
      "Acreditación por certificado Udemy Computación, Si tomaste uno o varios módulos de nivelación de Introducción a la Computación MOOC ofrecidos en la plataforma Udemy ",
    Favorito: false,
    FechaCreacion: "/Date(1606945986000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-08-06 00:05:00 -06:00",
      Milisegundos: "/Date(1565071500000-0600)/",
    },
    Icono: "https://i.imgur.com/j2wCyRh.png",
    Id: 68,
    ImagenFondo: "",
    Nombre: "Acreditación por certificado Udemy Computación",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Acreditación | certificado | Udemy | computación",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Admitidos/03_T21.html",
  },
  {
    Acceso: "",
    Agrupacion: "#Recursos de apoyo#Programas en Linea",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_BIBLIOTECA",
    Descripcion: "Biblioteca Tec",
    Favorito: false,
    FechaCreacion: "/Date(1606945986000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-08-02 11:00:00 -06:00",
      Milisegundos: "/Date(1564765200000-0600)/",
    },
    Icono: "https://i.imgur.com/z3qMJ7D.png",
    Id: 69,
    ImagenFondo: "",
    Nombre: "Biblioteca Tec",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Biblioteca | libros",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "Nueva ventana",
    URL: "https://biblioteca.tec.mx/inicio",
  },
  {
    Acceso: "",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_002",
    Descripcion:
      "Información del software disponible para descarga para alumnos del Tecnológico de Monterrey",
    Favorito: false,
    FechaCreacion: "/Date(1606945987000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/5lXG6A6.png",
    Id: 70,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Mas_visitados/software.png",
    Nombre: "Software en convenio",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Software | programa | convenio | convenios | programas | word | excel\t | Software | program | agreement | conventions | programs | word | Excel",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitec.itesm.mx/sites/talentoycultura/Mi%20compensacion/SoftwareConvenio.html",
  },
  {
    Acceso: "",
    Agrupacion: "#Recursos de apoyo",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_GUIALUM",
    Descripcion:
      "Tutoriales de las tecnologías educativas del Modelo Educativo Tec21 ",
    Favorito: false,
    FechaCreacion: "/Date(1606945988000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-08-02 11:00:00 -06:00",
      Milisegundos: "/Date(1564765200000-0600)/",
    },
    Icono: "https://i.imgur.com/i0nayMw.png",
    Id: 72,
    ImagenFondo: "",
    Nombre: "Tutoriales de tecnología educativa",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Tutorial | tutoriales | tecnología | educativa",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "Nueva ventana",
    URL: "https://sites.google.com/tec.mx/canvas/alumnos",
  },
  {
    Acceso: "",
    Agrupacion: "#Recursos de apoyo",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_GUIAT21",
    Descripcion:
      "Modelo educativo Tec 21, la guía básica, práctica e ilistrada.\r\nFamiliarízate con los conceptos asociados al modelo Tec21 \r\n \r\n",
    Favorito: false,
    FechaCreacion: "/Date(1606945991000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-08-01 11:00:00 -06:00",
      Milisegundos: "/Date(1564678800000-0600)/",
    },
    Icono: "https://i.imgur.com/uwsNDKj.png",
    Id: 77,
    ImagenFondo: "",
    Nombre: "Tec 21 la guía básica",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Guía | guías | información | modelo | educativo",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "Nueva ventana",
    URL: "https://tec.mx/es/la-guia-tec21",
  },
  {
    Acceso: "",
    Agrupacion: "#Programas en Linea",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_ECOASED ",
    Descripcion:
      "Encuestas de opinión de Estudiantes sobre Profesores, Materias o Unidades de Formación, Servicios Acádemicos.",
    Favorito: false,
    FechaCreacion: "/Date(1606945993000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-09-09 10:00:00 -06:00",
      Milisegundos: "/Date(1568044800000-0600)/",
    },
    Icono: "https://i.imgur.com/zH7OASc.png",
    Id: 80,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/ECOA.png",
    Nombre: "(ECOA) Encuesta de Opinión de Alumnos ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "ECOA | encuesta  | survey | pulse check",
    Popularidad: 0,
    Subcategoria: "Encuestas",
    TipoIntegracion: "Nueva ventana",
    URL: "https://encuestastec.itesm.mx/users/auth/saml",
  },
  {
    Acceso: "",
    Agrupacion: "#LIFE",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SISTEMA_24A_CVC",
    Descripcion:
      "Información y aplicación a a las opciones de prácticas profesionales y trabajos de tiempo completo.",
    Favorito: false,
    FechaCreacion: "/Date(1606945994000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-09-19 00:00:00 -06:00",
      Milisegundos: "/Date(1568872800000-0600)/",
    },
    Icono: "https://i.imgur.com/KJW24Mz.png",
    Id: 81,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/bolsa%20de%20trabajo.png",
    Nombre: "Bolsa de Trabajo",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "trabajo | búsqueda de trabajo | oferta laboral | bolsa | vacantes | busqueda de trabajo | work | job search | job offer | vacancie",
    Popularidad: 0,
    Subcategoria: "Bolsa de Trabajo",
    TipoIntegracion: "Nueva ventana",
    URL: "https://shibboleth-tecmx-csm.symplicity.com/sso/",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "Alumn_PEAlumSAMP ",
    Descripcion:
      "Consulta de materias o unidades de formación que forman tu plan de estudios para el logro de los Objetivos de Aprendizaje",
    Favorito: false,
    FechaCreacion: "/Date(1606945995000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-10-08 01:00:00 -06:00",
      Milisegundos: "/Date(1570518000000-0600)/",
    },
    Icono: "https://i.imgur.com/j2wCyRh.png",
    Id: 82,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/plan%20de%20estudios.png",
    Nombre: "Mi plan de estudios ",
    OrdenRecomendado: 1,
    PaginaIntermedia: "",
    PalabrasClave:
      "plan de estudios | programa académico | clases | programa | estudios | materias | programa academico | study plan | academic program | classes | program | studies | subjects",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://sampvc.itesm.mx/home/index ",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo",
    Clave: "Alum_tutorial Formalización Préstamo Educativo",
    Descripcion:
      "Con la intención de brindar un buen servicio, eficiente y homologado se ha diseñadoun video tutorial para alumnos que apoye el proceso de formalización del préstamo",
    Favorito: false,
    FechaCreacion: "/Date(1606945995000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/jpPSgNj.png",
    Id: 83,
    ImagenFondo: "",
    Nombre: "Video tutorial de Formalización de Préstamo Educativo",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "tutorial | tutoriales | vídeo | videos | formalización | préstamo | préstamos | educativo",
    Popularidad: 0,
    Subcategoria: "Becas y Créditos",
    TipoIntegracion: "Nueva ventana",
    URL: "https://vimeo.com/225919224",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_Cambio_carrera ",
    Descripcion: "Solicitud para el cambio de carrera de egreso tec21",
    Favorito: false,
    FechaCreacion: "/Date(1606945996000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-03-08 00:05:00 -06:00",
      Milisegundos: "/Date(1678255500000-0600)/",
    },
    Icono: "https://i.imgur.com/mcOQHC9.png",
    Id: 85,
    ImagenFondo: "",
    Nombre: "Cambio de Carrera de egreso ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "cambio | cambios | carrera | egreso | Tec21 | Tec 21",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Cambio/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Graduaciones",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_GRD_2014 ",
    Descripcion:
      "Información general en el proceso de graduación y trámites que deberás seguir para la obtención de tu diploma, título o grado académico además de los accesos a los sistemas relacionados a la graduación.",
    Favorito: false,
    FechaCreacion: "/Date(1606945997000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-10-23 10:00:00 -06:00",
      Milisegundos: "/Date(1571846400000-0600)/",
    },
    Icono: "https://i.imgur.com/SI6SQeC.png",
    Id: 86,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/graduacion.png",
    Nombre: "Proceso de Graduación ",
    OrdenRecomendado: 1,
    PaginaIntermedia: "",
    PalabrasClave:
      "graduación | proceso de graduación | requisitos de graduación | graduarme \t | graduation | graduation process | graduation requirements | graduate",
    Popularidad: 0,
    Subcategoria: "Trámites de graduación",
    TipoIntegracion: "En sitio",
    URL: "https://alsvdbw01.itesm.mx/student/graduaciones/ServGrad/index.html ",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_TRANSFERENCIAS_PROFT21",
    Descripcion:
      "Encuentra toda la información sobre el proceso de transferencias entre campus",
    Favorito: false,
    FechaCreacion: "/Date(1606945998000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-03-08 00:05:00 -06:00",
      Milisegundos: "/Date(1678255500000-0600)/",
    },
    Icono: "https://i.imgur.com/mcOQHC9.png",
    Id: 89,
    ImagenFondo: "",
    Nombre: "Solicitud de Transferencia",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Solicitud | cambio | transferencia | transferencias",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Transferencias_21/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios en Campus",
    Clave: "ALUM_SIS_RESIDENCIAS",
    Descripcion:
      "Reservación servicio de hospedaje en Residencias en los campus donde tenemos presencia: MTY, GDL, QRO, PUE, LEO y CHI\r\n",
    Favorito: false,
    FechaCreacion: "/Date(1606946003000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-12-11 00:00:00 -06:00",
      Milisegundos: "/Date(1576044000000-0600)/",
    },
    Icono: "https://i.imgur.com/vRmla0y.jpg",
    Id: 97,
    ImagenFondo: "",
    Nombre: "Residencias",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Residencia | residencias | cuarto | cuartos | vivienda | vivir | estancia",
    Popularidad: 0,
    Subcategoria: "Residencias",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_CAMPUS/Residencias/Residencias/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#TesorerÍa",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_Cuotas",
    Descripcion: "Cuotas de Colegiatura y Políticas de Pago (Reembolsos)",
    Favorito: false,
    FechaCreacion: "/Date(1606945918000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-08 18:00:00 -06:00",
      Milisegundos: "/Date(1554768000000-0600)/",
    },
    Icono: "https://i.imgur.com/9fNYwUZ.png",
    Id: 108,
    ImagenFondo: "",
    Nombre: "Cuotas de Colegiatura y Políticas de Pago (Reembolsos)",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Reembolso | reembolsos | cuota | cuotas | colegiatura | colegiaturas | pago | pagos | política | políticas",
    Popularidad: 0,
    Subcategoria: "Servicios de Tesoreria",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/MIInscripcion/index_CUOTAS.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Recursos de apoyo",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_bits",
    Descripcion:
      "Modelo educativo Tec 21, la guía básica, práctica e ilistrada. \r\nFamiliarízate con los conceptos asociados al modelo Tec21 \r\n",
    Favorito: false,
    FechaCreacion: "/Date(1606945920000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-11-23 11:00:00 -06:00",
      Milisegundos: "/Date(1574528400000-0600)/",
    },
    Icono: "https://i.imgur.com/YmtyVon.png",
    Id: 111,
    ImagenFondo: "",
    Nombre: "Bits & tips",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Bit | bits | tip | tips",
    Popularidad: 0,
    Subcategoria: "Tec Services",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitec.itesm.mx/sites/tutoriales/bits_tips/SitePages/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#LIFE",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS_LIFEHOME",
    Descripcion:
      "En LiFE nos preocupamos para que continúes desarrollando competencias y fomentando tu bienestar integral.",
    Favorito: false,
    FechaCreacion: "/Date(1606945923000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-04-13 01:00:00 -06:00",
      Milisegundos: "/Date(1586761200000-0600)/",
    },
    Icono: "https://i.imgur.com/zOpgWs6.png",
    Id: 116,
    ImagenFondo: "",
    Nombre: "LiFE at home",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Life |  home | extracurricular | esxtracurriculares | deporte | deportes | bienestar",
    Popularidad: 0,
    Subcategoria: "LiFE - Liderazgo y Formacion Estudiantil",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitec.itesm.mx/sites/ModeloFlexibleDigital/Paginas/life-home.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "alum_Resultados de evalución inicial",
    Descripcion:
      "En esta sección encontrarás los resultados de la evaluación inicial realizada como parte de tu proceso de admisión e inscripción al Tec.",
    Favorito: false,
    FechaCreacion: "/Date(1606945926000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-05-18 10:00:00 -06:00",
      Milisegundos: "/Date(1589817600000-0600)/",
    },
    Icono: "https://i.imgur.com/HRaANvr.png",
    Id: 120,
    ImagenFondo: "",
    Nombre: "Resultados de evaluación inicial",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Resultado | resultados | examen | exámenes | evaluación | prueba | inicial | inicio",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Integrado",
    URL: "https://resultadosadmisiones.tec.mx",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Recursos de apoyo",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_HyFlexPlus",
    Descripcion: "HyFlexPlus",
    Favorito: false,
    FechaCreacion: "/Date(1606945928000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-07-09 11:00:00 -06:00",
      Milisegundos: "/Date(1594314000000-0600)/",
    },
    Icono: "https://i.imgur.com/opPs3h7.jpg",
    Id: 124,
    ImagenFondo: "",
    Nombre: "HyFlexPlus",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Hyflex | curso | cursos | digital | digitales | Hyflexplus",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitec.itesm.mx/sites/Academia/Cursos/HyFlexPlus/",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Diplomas",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_Diploma_Inter",
    Descripcion:
      "Es una distinción especial que reconoce el perfil que desarrollarás en un ámbito internacional. Al egresar, los estudiantes participantes reciben, adicional a su título profesional",
    Favorito: false,
    FechaCreacion: "/Date(1606945930000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-10-16 18:00:00 -06:00",
      Milisegundos: "/Date(1602892800000-0600)/",
    },
    Icono: "https://i.imgur.com/3OvlEe0.png",
    Id: 127,
    ImagenFondo: "",
    Nombre: "Diploma Internacional",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Certificado extranjero | diploma internacional | doble grado\r\n",
    Popularidad: 0,
    Subcategoria: "Programas Internacionales",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Servicios/Diploma_internacional/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_MULTIPLATAFORMA ",
    Descripcion:
      "Permite visualizar las ofertas de diferentes eventos del estudiante. Muestra la oferta para que los estudiantes puedan postularse",
    Favorito: false,
    FechaCreacion: "/Date(1606945932000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-09-02 00:00:00 -06:00",
      Milisegundos: "/Date(1599026400000-0600)/",
    },
    Icono: "https://i.imgur.com/8Brg1DK.png",
    Id: 130,
    ImagenFondo: "",
    Nombre: "Multiplataforma",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "multiplataforma | oferta | postulación | eventos | calendario",
    Popularidad: 0,
    Subcategoria: "Plataformas educativas",
    TipoIntegracion: "Nueva ventana",
    URL: "https://multiplataforma.tec.mx",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#TesorerÍa",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_PIE",
    Descripcion:
      "En esta sección podrás acceder al portal del Plan de Inversión Educativa",
    Favorito: false,
    FechaCreacion: "/Date(1606945933000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-09-20 00:00:00 -06:00",
      Milisegundos: "/Date(1600581600000-0600)/",
    },
    Icono: "https://i.imgur.com/WcqYnDM.png",
    Id: 132,
    ImagenFondo: "",
    Nombre: "Plan de Inversión Educativa",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "PIE | plan | inversión | inversion | educativa | certifcado | certificados | colegiatura | colegiaturas",
    Popularidad: 0,
    Subcategoria: "Becas y Créditos",
    TipoIntegracion: "Nueva ventana",
    URL: "https://pie.tec.mx/?utm_source=MiTec&utm_medium=Portal&utm_campaign=Nacional&utm_term=Web&utm_content=ME",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIIP_CVU",
    Descripcion:
      "Que pueda tener su curriculo en formato extendido solicitado por el Conacyt.",
    Favorito: false,
    FechaCreacion: "/Date(1606945943000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-10-24 19:26:00 -06:00",
      Milisegundos: "/Date(1603589160000-0600)/",
    },
    Icono: "https://i.imgur.com/tyP0cDo.png",
    Id: 175,
    ImagenFondo: "",
    Nombre: "Curriculum Vitae: CONACYT (CVU)",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "curriculum | vitae | Conacyt",
    Popularidad: 0,
    Subcategoria: "Centro de Vinculación y Desarrollo Profesional",
    TipoIntegracion: "Nueva ventana",
    URL: "http://people.conacyt.mx/registros/",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_CANVAS",
    Descripcion:
      "Plataforma Académica donde se encuentran el material de estudio de las Materias o Unidades de Formación",
    Favorito: false,
    FechaCreacion: "/Date(1606945945000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-10-24 19:26:00 -06:00",
      Milisegundos: "/Date(1603589160000-0600)/",
    },
    Icono: "https://i.imgur.com/osfN7zp.png",
    Id: 179,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/Canva.png",
    Nombre: "Canvas",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "canvas | cursos | materias | plataforma\t | courses | subjects | platform | academica | académica",
    Popularidad: 0,
    Subcategoria: "Plataformas educativas",
    TipoIntegracion: "Nueva ventana",
    URL: "https://experiencia21.tec.mx",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_ECAG",
    Descripcion:
      "Encuestas para aplicacion de la encuesta a alumnos candidatos a graduar para todos los niveles y campus",
    Favorito: false,
    FechaCreacion: "/Date(1606945947000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-10-24 19:26:00 -06:00",
      Milisegundos: "/Date(1603589160000-0600)/",
    },
    Icono: "https://i.imgur.com/dEZht3H.png",
    Id: 181,
    ImagenFondo: "",
    Nombre: "Encuesta Candidatos a Graduar (ECAG)",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "ECAG | encuesta | graduado | graduados | graduación | candidato | canditados",
    Popularidad: 0,
    Subcategoria: "Trámites de graduación",
    TipoIntegracion: "Nueva ventana",
    URL: "https://encuestastec.itesm.mx/users/auth/saml",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_TECSTORE",
    Descripcion:
      "Conoce TECstore en linea. La pagina de los productos oficiales del Tecnologico de Monterrey.",
    Favorito: false,
    FechaCreacion: "/Date(1606945949000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-10-24 19:26:00 -06:00",
      Milisegundos: "/Date(1603589160000-0600)/",
    },
    Icono: "https://i.imgur.com/HqNTV6v.png",
    Id: 185,
    ImagenFondo: "",
    Nombre: "TECstore en linea",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Market | tienda | línea | store | compra",
    Popularidad: 0,
    Subcategoria: "Tec Store",
    TipoIntegracion: "Nueva ventana",
    URL: "https://market.tec.mx/tecstore",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "Alum_Integridad Académica",
    Descripcion:
      "Espacio donde el alumno podrá conocer más sobre el Fortalecimiento de la Integridad Académica",
    Favorito: false,
    FechaCreacion: "/Date(1606945958000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2018-03-07 00:00:00 -06:00",
      Milisegundos: "/Date(1520402400000-0600)/",
    },
    Icono: "https://i.imgur.com/LnO7NR2.png",
    Id: 201,
    ImagenFondo: "",
    Nombre: "Integridad Académica",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "código | codigo | integridad | académica | academica",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "http://sitios.itesm.mx/dfds/ssc/Alumnos/contenido/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_Guíaccesocorreo",
    Descripcion:
      "Guía de configuración para el ingreso a correo electrónico y re envío a otra cuenta de correo o gmail",
    Favorito: false,
    FechaCreacion: "/Date(1606945960000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2019-04-03 00:00:00 -06:00",
      Milisegundos: "/Date(1554271200000-0600)/",
    },
    Icono: "https://i.imgur.com/HWuzDmr.png",
    Id: 204,
    ImagenFondo: "",
    Nombre: "Guía de acceso a tu correo y re envío",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "guía | guías | acceso | correo | correos | mail",
    Popularidad: 0,
    Subcategoria: "Tec Services",
    TipoIntegracion: "Nueva ventana",
    URL: "http://sitios.itesm.mx/va/tutoriales/alumnos/PRM_INGRESO/manuales/Guia_Acceso_Mail_FWR.pdf",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS_DIGNI_HUMANA",
    Descripcion: "Reporte Transparencia Centro Dignidad Humana",
    Favorito: false,
    FechaCreacion: "/Date(1608332305000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2020-12-18 17:00:00 -06:00",
      Milisegundos: "/Date(1608332400000-0600)/",
    },
    Icono: "https://i.imgur.com/n4KFhTN.jpg",
    Id: 216,
    ImagenFondo: "",
    Nombre: "Centro de Reconocimiento de la Dignidad Humana",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "centro | reconocimiento | dignidad | humana | inclusión",
    Popularidad: 0,
    Subcategoria: "Seguros y Bienestar",
    TipoIntegracion: "Nueva ventana",
    URL: "https://tec.mx/es/dignidad-humana/transparencia",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_INF_PIE",
    Descripcion:
      "Servicio informativo sobre el proceso para hacer validos tus certificados PIE al momento de tu inscripción.",
    Favorito: false,
    FechaCreacion: "/Date(1614204935000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-02-23 00:00:00 -06:00",
      Milisegundos: "/Date(1614060000000-0600)/",
    },
    Icono: "https://i.imgur.com/JUANPJ8.png",
    Id: 229,
    ImagenFondo: "",
    Nombre: "Conoce el Plan Inversión Educativa (PIE) ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "PIE | plan | inversión | inversion | educativa | certifcado | certificados | colegiatura | colegiaturas",
    Popularidad: 0,
    Subcategoria: "Becas y Créditos",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/servicios/Ser_Pie/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_INF_PAGO_LINEA",
    Descripcion:
      "Servicio informativo para pagar desde tu estado de cuenta web",
    Favorito: false,
    FechaCreacion: "/Date(1616703800000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-02-23 00:00:00 -06:00",
      Milisegundos: "/Date(1614060000000-0600)/",
    },
    Icono: "https://i.imgur.com/WmoOZvf.png",
    Id: 271,
    ImagenFondo: "",
    Nombre: "Pago desde Tu Estado de cuenta web",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Pago | pagos | estado | cuenta | internet | web | cuentas",
    Popularidad: 0,
    Subcategoria: "Servicios de Tesoreria",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Servicios/Ser_Pago_enlinea/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_TUINFO",
    Descripcion:
      "Con el fin de proteger a todos los integrantes de nuestra Institución de posibles ciberataques (robo de información e identidad por medios electrónicos) estamos implementando:\r\n- MI  llave digital\r\n- Migración a @tec.mx",
    Favorito: false,
    FechaCreacion: "/Date(1620344220000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-05-05 05:00:00 -06:00",
      Milisegundos: "/Date(1620212400000-0600)/",
    },
    Icono: "https://i.imgur.com/fpWKVJF.png",
    Id: 303,
    ImagenFondo: "",
    Nombre: "Protege tu información",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Protege | proteger | protección | datos | información",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/academia/servicios/PROTEGE_INFO/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "Alumn_SIS_HEA21",
    Descripcion:
      "El Programa de Desarrollo de Habilidades para el Éxito Académico tiene como propósito apoyar a los alumnos inscritos en planes de estudio edición 2019 y posteriores en su desarrollo académico.",
    Favorito: false,
    FechaCreacion: "/Date(1620667100000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-05-10 00:00:00 -06:00",
      Milisegundos: "/Date(1620626400000-0600)/",
    },
    Icono: "https://i.imgur.com/XOPjRb3.png",
    Id: 304,
    ImagenFondo: "",
    Nombre:
      "Programa para el Desarrollo de Habilidades para el Éxito Académico",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Programa | programas | desarrollo | habilidad | habilidades | éxito | éxito | academico | académico",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "En sitio",
    URL: "https://samp.itesm.mx/Programas/VistaPrograma?clave=hea21&modoVista=Default&idioma=ES&cols=0",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Acreditaciones",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_NIVELACIÓN",
    Descripcion:
      "Cursos opcionales y digitales que buscan reforzar tu idioma inglés y distintas disciplinas",
    Favorito: false,
    FechaCreacion: "/Date(1621613703000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-06-14 00:00:00 -06:00",
      Milisegundos: "/Date(1623650400000-0600)/",
    },
    Icono: "https://i.imgur.com/gD5OxVY.png",
    Id: 306,
    ImagenFondo: "",
    Nombre: "Nivelación Flexible",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "nivelación | cursos | coursera | revalidación | remediales\r\n",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Servicios/NIVELACION_FLEXIBLE/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_ULEAD",
    Descripcion: "Diploma U LEAD un programa por invitación ",
    Favorito: false,
    FechaCreacion: "/Date(1622151612000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-05-27 00:00:00 -06:00",
      Milisegundos: "/Date(1622095200000-0600)/",
    },
    Icono: "https://i.imgur.com/WkMScqk.png",
    Id: 307,
    ImagenFondo: "",
    Nombre: "Diploma U-LEAD",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "diploma | Ulead | u lead | u-lead | acreditación",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Cursos/Diploma_ULEAD/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_DominioIN",
    Descripcion:
      "En esta sección podrás consultar opciones para acreditar el idioma inglés (requisito para graduar).",
    Favorito: false,
    FechaCreacion: "/Date(1623180449000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-06-08 00:00:00 -06:00",
      Milisegundos: "/Date(1623132000000-0600)/",
    },
    Icono: "https://i.imgur.com/4DWP7Q6.png",
    Id: 312,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/Dominio%20del%20idioma%20ingl%C3%A9s.png",
    Nombre: "Dominio del idioma inglés",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "estudia inglés | clases de inglés | clases | TOEFL | inglés | idiomas\r\n",
    Popularidad: 0,
    Subcategoria: "Idiomas",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/academia/servicios/Dominio_id_ingles/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Información#Escolar",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_ENVIO_FOTO",
    Descripcion:
      "En este servicio podrás enviar tu fotografía para tu credencial como alumno inscrito de nuevo ingreso al Tecnológico de Monterrey",
    Favorito: false,
    FechaCreacion: "/Date(1623781119000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-08-18 16:00:00 -06:00",
      Milisegundos: "/Date(1629324000000-0600)/",
    },
    Icono: "https://i.imgur.com/jkzbiZl.png",
    Id: 313,
    ImagenFondo: "",
    Nombre: "Envío de fotografía",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "foto | fotos | fotografía | fotografías | fotografia | fotografias | credencial | crede | identificación",
    Popularidad: 0,
    Subcategoria: "Mi perfil",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_ACADEMICO/Servicios%20Escolares/Envio_Foto/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Recursos de apoyo",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_HyFlexPlus2",
    Descripcion: "HyFlex+Tec Cursos Digitales",
    Favorito: false,
    FechaCreacion: "/Date(1623945204000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-06-17 00:00:00 -06:00",
      Milisegundos: "/Date(1623909600000-0600)/",
    },
    Icono: "https://i.imgur.com/v5EFyXF.jpg",
    Id: 314,
    ImagenFondo: "",
    Nombre: "HyFlex+Tec Cursos Digitales",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Hyflex | curso | cursos | digital | digitales",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/PublishingImages/Inscripciones/tabla-experiencias-cursos-digitales.pdf",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_Experiencias-TEC-i ",
    Descripcion:
      "Oferta de Experiencias TEC/i para verano, inviernos, semestres en los diferentes campus del país.",
    Favorito: false,
    FechaCreacion: "/Date(1624403710000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-06-22 10:00:00 -06:00",
      Milisegundos: "/Date(1624377600000-0600)/",
    },
    Icono: "https://i.imgur.com/GNaprSl.png",
    Id: 317,
    ImagenFondo: "",
    Nombre: "Experiencias TEC/i ",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Experiencia | excperiencias | Tec | i | semana | semestre",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://experiencia.tec.mx/es",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios en Campus",
    Clave: "ALUM_CCM_MOV",
    Descripcion: "Transporte CCM",
    Favorito: false,
    FechaCreacion: "/Date(1625859395000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-07-08 00:00:00 -06:00",
      Milisegundos: "/Date(1625724000000-0600)/",
    },
    Icono: "https://i.imgur.com/AqPszfp.png",
    Id: 320,
    ImagenFondo: "",
    Nombre: "Transporte",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Expreso | transporte | Tec | camión | camiones | movilidad",
    Popularidad: 0,
    Subcategoria: "Transporte",
    TipoIntegracion: "En sitio",
    URL: "https://portalrep.itesm.mx/va_rep/Movilidad_centro/life/transporteCCM.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_TIENDAV_V_2018",
    Descripcion:
      "¡Tus compras en un mismo lugar! Ingresa a Market Tec donde podrás adquirir tus productos favoritos y servicios del Tec de Monterrey",
    Favorito: false,
    FechaCreacion: "/Date(1627344950000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-08-01 11:00:00 -06:00",
      Milisegundos: "/Date(1627837200000-0600)/",
    },
    Icono: "https://i.imgur.com/CKBvCAs.jpg",
    Id: 324,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/Market%20TEC.png",
    Nombre: "Market Tec (Compras en línea)",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Market | tienda | linea | store | compra | internet | línea",
    Popularidad: 0,
    Subcategoria: "Tec Store",
    TipoIntegracion: "Nueva ventana",
    URL: "https://market.tec.mx/login?samltec",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "Alum_SIS_ModeloTec",
    Descripcion:
      "Conoce a las personas clave durante las siguientes etapas en el TEC: Exploración, Enfoque y Especilización. Ellos te guiarán para tomar las mejores decisiones e impulsar tu formación integral.",
    Favorito: false,
    FechaCreacion: "/Date(1630018125000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-08-26 00:00:00 -06:00",
      Milisegundos: "/Date(1629957600000-0600)/",
    },
    Icono: "https://i.imgur.com/OwUdXkq.png",
    Id: 333,
    ImagenFondo: "",
    Nombre: "Modelo de Acompañamiento",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "modelo | acompamiento | consejería | consejeros | exploración | enfoque",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Servicios/Mentor/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS_miVidaTec",
    Descripcion:
      "Un espacio digital para que visualices información clave de quién eres hoy, para que reflejes lo que te gusta, puedas plasmar tu propósito de vida y tus metas y puedas interactuar con personas clave para hacer realidad esta versión de lo que quieres llegar a ser",
    Favorito: false,
    FechaCreacion: "/Date(1634678652000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-10-18 00:00:00 -06:00",
      Milisegundos: "/Date(1634536800000-0600)/",
    },
    Icono: "https://i.imgur.com/hSgP8aT.png",
    Id: 338,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/Life@tec.png",
    Nombre: "miVidaTec",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Vida | mividatec | life |  home | extracurricular | esxtracurriculares | deporte | deportes | bienestar | Mi vida",
    Popularidad: 0,
    Subcategoria: "LiFE - Liderazgo y Formacion Estudiantil",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/expediente360/Paginas/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "Alum_reglamentos",
    Descripcion: "Reglamentos",
    Favorito: false,
    FechaCreacion: "/Date(1634829410000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-11-15 00:00:00 -06:00",
      Milisegundos: "/Date(1636956000000-0600)/",
    },
    Icono: "https://i.imgur.com/iUDtRkt.png",
    Id: 339,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/Reglamentos.png",
    Nombre: "Reglamentos",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Reglamento | reglamentos | política | políticas | lineamiento | lineamientos",
    Popularidad: 0,
    Subcategoria: "Reglamentos",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/servicios/Reglamentos/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_Progm_becas",
    Descripcion:
      "Fomenta el fortalecimiento de competencias, habilidades y conocimientos en los estudiantes becados, mediante su participación en proyectos institucionales generados por profesores y colaboradores",
    Favorito: false,
    FechaCreacion: "/Date(1638228935000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-09-29 00:00:00 -06:00",
      Milisegundos: "/Date(1664431200000-0600)/",
    },
    Icono: "https://i.imgur.com/IifSfCC.png",
    Id: 342,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/becarios.png",
    Nombre: "Programa de Becarios",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Beca | becas | becario | programa | programas | Scholarship | scholarships | intern | program | programs | Programa de Becarios | Becarios | Servicio Becario",
    Popularidad: 0,
    Subcategoria: "Becas y Créditos",
    TipoIntegracion: "Nueva ventana",
    URL: "https://programadebecarios.tec.mx",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Seguros y Bienestar",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SIS_TQueremos",
    Descripcion: "TQueremos estuadiantes",
    Favorito: false,
    FechaCreacion: "/Date(1639605596000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2021-12-15 00:00:00 -06:00",
      Milisegundos: "/Date(1639548000000-0600)/",
    },
    Icono: "https://i.imgur.com/wPYz1WX.png",
    Id: 344,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/TQueremos.png",
    Nombre: "TQueremos",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Tqueremos | queremos",
    Popularidad: 0,
    Subcategoria: "Seguros y Bienestar",
    TipoIntegracion: "Nueva ventana",
    URL: "https://tqueremos.tec.mx/",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Servicio Social",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_SS",
    Descripcion:
      "Proceso e información para actividad profesional a través de cuya práctica, el estudiante participa en la sociedad, identificando problemáticas y coadyuvando a su solución",
    Favorito: false,
    FechaCreacion: "/Date(1641532904000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-06-06 08:00:00 -06:00",
      Milisegundos: "/Date(1654524000000-0600)/",
    },
    Icono: "https://i.imgur.com/Ct5Gsbo.png",
    Id: 346,
    ImagenFondo: "",
    Nombre: "Servicio Social",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "servicio social | servicio profesional | horas | servicio | social | Avance | Servicio | Social | SIASS | Horas | SS | Campus |  Responsables | Historial | Unidades | Formación | Plataforma | Iniciativas, Sociales\t | social service | professional service | hours | service | society | Advance | Service | Community | SIASS | Hours | SS | Campuses | Responsible | History | Units | Training | Platform | Initiatives, Social",
    Popularidad: 0,
    Subcategoria: "Servicio Social",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Servicios/Servicio_Social/index_T21.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Inscripción",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_DFHORZ",
    Descripcion:
      "Aquí podrás elegir tu Carrera, Semestre Tec, Cambio de Entrada o Carrera, Doble Titulación y Área de Estudio (IID/LAD/LDI)",
    Favorito: false,
    FechaCreacion: "/Date(1644018916000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-03-08 00:05:00 -06:00",
      Milisegundos: "/Date(1678255500000-0600)/",
    },
    Icono: "https://i.imgur.com/dZYCewG.png",
    Id: 351,
    ImagenFondo: "",
    Nombre: "Definiendo Horizontes, Semestre Tec, Elección carrera",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "cambio | cambios | etapa | definiendo | horizontes  | Tec 21 | Mi Trayectoria | mitrayectoria",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://mitrayectoria.tec.mx",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Mi Información",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "Alumn_SIS_CIC_2022",
    Descripcion: "Centro Internacional de Casos",
    Favorito: false,
    FechaCreacion: "/Date(1650570598000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-04-21 13:35:00 -06:00",
      Milisegundos: "/Date(1650569700000-0600)/",
    },
    Icono: "https://i.imgur.com/BHunZNn.png",
    Id: 356,
    ImagenFondo: "",
    Nombre: "CIC",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "CIC | Casos | Centro",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "Nueva ventana",
    URL: "https://cic.itesm.mx/_layouts/15/Authenticate.aspx?Source=%2FPaginas%2Fdefault%2Easpx",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_Constancia",
    Descripcion:
      "Consulta y descarga de manera digital las constancias más utilizadas",
    Favorito: false,
    FechaCreacion: "/Date(1655416576000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-06-16 00:00:00 -06:00",
      Milisegundos: "/Date(1655359200000-0600)/",
    },
    Icono: "https://i.imgur.com/348rPU8.jpg",
    Id: 359,
    ImagenFondo:
      "https://mitec.itesm.mx/Alumnos/PublishingImages/Recomendados/constancias.png",
    Nombre: "Mis Constancias",
    OrdenRecomendado: 1,
    PaginaIntermedia: "",
    PalabrasClave: "Constancia | cartas | documentos | estudios \r\n",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://constanciasestudiantes.tec.mx/",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_EST_INT",
    Descripcion:
      "Información para estudiantes extranjeros de oferta y trámites para estudiar en el Tec de Monterrey",
    Favorito: false,
    FechaCreacion: "/Date(1656095295000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-06-27 08:00:00 -06:00",
      Milisegundos: "/Date(1656338400000-0600)/",
    },
    Icono: "https://i.imgur.com/CvGCjyI.png",
    Id: 361,
    ImagenFondo: "",
    Nombre: "Estudiantes Internacionales",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Extranjero | International | Program | Visit | Programas | Internacionales | Internacional | Foreign | Estudia",
    Popularidad: 0,
    Subcategoria: "Programas Internacionales",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Programas_Internacionales/EstudiantesInternacionales/PI_internacionalesEN.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "ALUM_SIS_PROGINT_prof",
    Descripcion:
      "Opciones de experiencias internacionales, trámites, reglamentos, convocatorias, etc.",
    Favorito: false,
    FechaCreacion: "/Date(1656113972000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-06-27 08:00:00 -06:00",
      Milisegundos: "/Date(1656338400000-0600)/",
    },
    Icono: "https://i.imgur.com/CvGCjyI.png",
    Id: 363,
    ImagenFondo: "",
    Nombre: "Mi Experiencia internacional profesional",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Mi experiencia internacional | Programas internacionales | Estudia en el extranjero | Mis Solicitudes PI | Catálogo PI Profesional | Internacionalización  | My international experience | International Programs | Study abroad | My PI Requests | Catalog | internationalization",
    Popularidad: 0,
    Subcategoria: "Programas Internacionales",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Programas_Internacionales/EstudiantesInternacionales/PI_profe.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_ADMS_2022",
    Descripcion:
      "Solicitud de admisión y becas para los programas del Tec de Monterrey",
    Favorito: false,
    FechaCreacion: "/Date(1661792102000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-08-29 00:00:00 -06:00",
      Milisegundos: "/Date(1661752800000-0600)/",
    },
    Icono: "https://i.imgur.com/26lpY3w.png",
    Id: 370,
    ImagenFondo: "",
    Nombre: "Solicitud de admisión y becas",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "admisión | beca | Solicitud Tec | solicitud | admision | ingreso |apoyo educativo | apoyo |  becas | admisiones |  scholarship | scholarships | admission | admissions | apoyo",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "Nueva ventana",
    URL: "https://solicitud.tec.mx/login?so=00D41000001NkaU",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_SEMANA_T",
    Descripcion: "Consultar la oferta de actividades para Semanas Tec ",
    Favorito: false,
    FechaCreacion: "/Date(1669129608000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2022-11-22 00:00:00 -06:00",
      Milisegundos: "/Date(1669096800000-0600)/",
    },
    Icono: "https://i.imgur.com/0DBSh65.png",
    Id: 378,
    ImagenFondo: "",
    Nombre: "Semanas Tec",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Semanas Tec | Semana | Tec | Cursos | Inscripción | Oferta | Competencias | Carrera | Semanas",
    Popularidad: 0,
    Subcategoria: "Servicios Escolares",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/servicios/ser_semanasTec/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "#Seguros y Bienestar",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SEGUROS",
    Descripcion:
      "Página para subir los documentos de cancelación de SGMM (Carta responsiva y carátula de póliza)",
    Favorito: false,
    FechaCreacion: "/Date(1673536315000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-01-24 08:00:00 -06:00",
      Milisegundos: "/Date(1674568800000-0600)/",
    },
    Icono: "https://i.imgur.com/lbivu5x.png",
    Id: 379,
    ImagenFondo: "",
    Nombre: "Mi Seguro de Gastos Médicos Mayores",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Seguro | seguros | gasto | gastos | médicos | cancelación | SGMM | accidentes  accidente",
    Popularidad: 0,
    Subcategoria: "Seguros y Bienestar",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/AUS/Paginas/Alumnos/Index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "",
    Clave: "",
    Descripcion: "Mis Donativos",
    Favorito: false,
    FechaCreacion: "/Date(1674343363000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-01-21 18:00:00 -06:00",
      Milisegundos: "/Date(1674345600000-0600)/",
    },
    Icono: "https://i.imgur.com/184dOWH.png",
    Id: 380,
    ImagenFondo: "",
    Nombre: "Mis Donativos",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "​​Mis donativos | donativos | donar | donación | dona | intervenir el futuro​​​​",
    Popularidad: 0,
    Subcategoria: "",
    TipoIntegracion: "En sitio",
    URL: "/Paginas/servicios/donantes/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo Académico",
    Clave: "ALUM_SIS_consejeros",
    Descripcion:
      "Durante la Reunión Anual de Consejeros 2023 del Tecnológico de Monterrey. Los invitamos a consultar los materiales exclusivos que tenemos para ustedes.",
    Favorito: false,
    FechaCreacion: "/Date(1678830674000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-03-14 00:00:00 -06:00",
      Milisegundos: "/Date(1678773600000-0600)/",
    },
    Icono: "https://i.imgur.com/rdKzyzm.jpg",
    Id: 383,
    ImagenFondo: "",
    Nombre: "Conferencias Reunión de Consejeros",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "",
    Popularidad: 0,
    Subcategoria: "Recursos de apoyo",
    TipoIntegracion: "Nueva ventana",
    URL: "/sites/ServColab/Institucional/Conferencias%20Reuni%C3%B3n%20de%20Consejeros/Conferencias2023.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "NOV_CON",
    Descripcion: "Sitio de consejos y novedades de mitec",
    Favorito: false,
    FechaCreacion: "/Date(1681403423000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-04-13 00:55:00 -06:00",
      Milisegundos: "/Date(1681368900000-0600)/",
    },
    Icono: "https://i.imgur.com/1HWblkU.png",
    Id: 387,
    ImagenFondo: "",
    Nombre: "Consejos y novedades",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "Consejos y novedades | Consejos en mitec| guia mitec | tutoriales |",
    Popularidad: 0,
    Subcategoria: "",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/Paginas/consejos%20y%20novedades/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Vida Estudiantil",
    Clave: "ALUM_SEGUROS_COBERTURAS",
    Descripcion:
      "Por que nos interesa tu salud y protección, encuentra aquí todo sobre tus seguros y coberturas.",
    Favorito: false,
    FechaCreacion: "/Date(1682527249000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-05-15 00:00:00 -06:00",
      Milisegundos: "/Date(1684130400000-0600)/",
    },
    Icono: "https://i.imgur.com/NvswJK6.png",
    Id: 391,
    ImagenFondo: "",
    Nombre: "Mis Seguros y Coberturas",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave:
      "| Seguros | SGMM | Coberturas | coberturas | pólizas | polizas | Pólizas | Polizas | facturación | Facturación | facturacion | Facturacion |",
    Popularidad: 0,
    Subcategoria: "Seguros y Bienestar",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/Academia/Servicios/Ser_SegCoberturas/index.html",
  },
  {
    Acceso: "0: Anónimo",
    Agrupacion: "",
    Categoria: "Servicios en Campus",
    Clave: "ALUM_SER_CAMP",
    Descripcion:
      "Servicios de Seguridad, Transporte, Comida, Instalaciones, Salud, Residencias, Lockers, Impresiones",
    Favorito: false,
    FechaCreacion: "/Date(1683917361000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-05-12 00:00:00 -06:00",
      Milisegundos: "/Date(1683871200000-0600)/",
    },
    Icono: "https://i.imgur.com/mwbi8op.png",
    Id: 392,
    ImagenFondo: "",
    Nombre: "mis Servicios en Campus",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "Servicios | Campus",
    Popularidad: 0,
    Subcategoria: "Seguridad",
    TipoIntegracion: "En sitio",
    URL: "https://mitec.itesm.mx/sites/ServAcad/S_VESTUDIANTIL/Mi%20Campus/En_campus/index.htm",
  },
  {
    Acceso: "",
    Agrupacion: "",
    Categoria: "Servicios de Apoyo",
    Clave: "",
    Descripcion: "Portafolio para subir evidencias",
    Favorito: false,
    FechaCreacion: "/Date(1683917361000-0600)/",
    FechaExpiracion: {
      FormatoISO: null,
      Milisegundos: "/Date(-62135575200000-0600)/",
    },
    FechaPublicacion: {
      FormatoISO: "2023-05-12 00:00:00 -06:00",
      Milisegundos: "/Date(1683871200000-0600)/",
    },
    Icono:
      "https://images.crunchbase.com/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1495225592/eqsylaxabhnkfh1tm3nj.png",
    Id: 392,
    ImagenFondo: "",
    Nombre: "Elumen",
    OrdenRecomendado: 0,
    PaginaIntermedia: "",
    PalabrasClave: "portafolio elumen evidencia",
    Popularidad: 0,
    Subcategoria: "Seguridad",
    TipoIntegracion: "En sitio",
    URL: "https://miscompetenciastec21.tec.mx",
  },
];

export default SERVICES;
